### ISSUE TITLE
[Bug] Unified search doesn't pick up Jira issues when search words contain Non-ascii characters

### ISSUE THREAD

**Issue by karl-in-office** [nextcloud/integration_jira#10]
[Environment]
Nextcloud: ver20.0.1
integration_jira: ver0.0.7 or higher (maybe existing from prior versions)

[Phenomenon]
As stated in the title, Unified search doesn't pick up Jira issues when search words contain Non-ascii characters. 

[Reproducibility]
Always (100%)

[Steps to reproduce]
1. Login to Nextcloud. 
2. Connect to self-hosted Jira. 
3. Put non-ascii characters in Unified search textbox. 

<img width="1286" alt="スクリーンショット 2020-11-17 14 16 00" src="https://user-images.githubusercontent.com/51474713/99349547-a1a9a600-28df-11eb-9161-90521d8ff36a.png">
<img width="1285" alt="スクリーンショット 2020-11-17 14 19 23" src="https://user-images.githubusercontent.com/51474713/99349841-49bf6f00-28e0-11eb-905e-336f5bfbb729.png">
<img width="1279" alt="スクリーンショット 2020-11-17 14 23 06" src="https://user-images.githubusercontent.com/51474713/99350048-cbaf9800-28e0-11eb-9ede-1b372a90b9a1.png">

**Comment by eneiluj** [comment]
It might be a problem on Jira's side. I'll check this out. Maybe it has been reported somewhere.

Thanks for the bug report!

**Comment by eneiluj** [comment]
Ok fixed in v0.0.10. Tough one. It was actually a problem on Jira's side. The `*` wildcard parameter does not work with non-ascii character in words. The solution is not ideal but it works: wildcards are now only used with full ascii words. So you have to type complete non-ascii words to get a result.

I'm interested in your feedback if you've got a chance to try v0.0.10.

**Comment by karl-in-office** [comment]
I've confirmed that this issue is solved with v0.0.10.
Thank you!
