### ISSUE TITLE
[Feature request] Restricting Jira URL

### ISSUE THREAD

**Issue by karl-in-office** [nextcloud/integration_jira#11]
Thank you for creating a wonderful app!

From regulated company's point of view, I would like to request a feature which limits self-hosted Jira URL. 
<img width="800" alt="スクリーンショット 2020-11-17 15 07 06" src="https://user-images.githubusercontent.com/51474713/99352944-e4bb4780-28e6-11eb-8a42-518be4cde957.png">

Because current this app allows to connect to any Jira instance. 
<img width="797" alt="スクリーンショット 2020-11-17 15 00 41" src="https://user-images.githubusercontent.com/51474713/99352343-cdc82580-28e5-11eb-94c7-ab9dd57b89c6.png">
However, it may violate not only company rules but laws (like GDPR). 
I would like to avoid such situation.

**Comment by jchavezb-37** [comment]
not working, javascript popup appears even when javascript is enabled in all browsers

**Comment by eneiluj** [comment]
@karl-in-office It's been a while... I like the idea and it was not too long to do it. This feature is included in v0.0.14 which is out. Could you try it?

If the admin URL restriction setting is set, the user setting address field is pre-filled and disabled.
For users who had already configured another self hosted Jira URL, each request will fail and return this error message : "Unauthorized Jira instance URL".

@jchavezb-37 This is unrelated to this issue. This happens because something wrong happens when trying to contact your Jira instance and it is not well handled by the app. I fixed a few things here and there in v0.0.14. Could you try it and tell me if it still happens?

I think your problem most likely is that your Jira instance can't be contacted.

**Comment by karl-in-office** [comment]
@eneiluj 
I've confirmed that my request is implemented in v0.0.14. Thanks!
I'll close this ticket now.
