### ISSUE TITLE
Support for onpremise Jira server

### ISSUE THREAD

**Issue by ntimo** [nextcloud/integration_jira#3]
Hello,
it seems like the jira integration for nextcloud currently only works with Jira Cloud. I think it would be awesome to be able to use it with self hosted jira since this would also match the nextcloud self hosted spirit. :) And also make it useable for a lot of companies who are not running in the cloud.

Thanks

**Comment by eneiluj** [comment]
It think so too. Thanks for the feedback.

Too bad the self hosted version is still proprietary and requires to buy a plan from them...pretty different spirit :grin:

The integration is now compatible with self hosted Jira! The authentication is less secure than with Jira Cloud because i couldn't find out how to manage OAuth stuff in the self hosted version and their documentation is...kind of good but it's easy to get lost in it.

If someone figures out how the he** OAuth can be used to authenticate to a self hosted Jira, PRs are very welcome.

So if you connect to a self hosted Jira, you have to provide your username and password which are stored hashed in NC. Be aware that at some point while developing, my account was "locked" and it was necessary to "unlock" it by logging in again with Jira's web interface.

You can try this new feature by building the app yourself or you can wait until the next release coming soon.
Cheers

**Comment by eneiluj** [comment]
New release is out. I'm very interested in your feedback :grin:.

**Comment by krejcar25** [comment]
Hello, I believe [this](https://bitbucket.org/atlassianlabs/atlassian-oauth-examples/src/master/php/) example code from Atlassian together with [this](https://developer.atlassian.com/server/jira/platform/oauth/) documentation page could be of use. Also @eneiluj if you'd be interested I own a DataCenter license and run a Jira server. I could test the integration for you or let you do it on my server.

If I understand the process correctly, Nextcloud would store a private key (literally a cryptographic private key) and would use that to request an OAuth ID and secret. These are valid for 10 minutes after which you need to request new pair if you need them. That sounds a little more complicated than normal OAuth but not too complicated.

I myself don't speak enough PHP to help write it myself but at least I can offer the testing environment. Message me here or on Matrix at [@krejcar25:blep.cz](https://matrix.to/#/@krejcar25:blep.cz) if you'd be interested.

**Comment by krejcar25** [comment]
UPDATE: Jira DC 8.22 supports standard OAuth 2.0, so the same method to auth against cloud service is used with the on-prem server. Changing the "Connect to Jira Cloud" button to just "Connect to Jira" and using the restricted URL from NC server settings should be simple now.
